### ISSUE TITLE
`seen.len` causes clash with actually serializable value `'len'`

### ISSUE THREAD

**Issue by nikki93** [gvx/bitser#12]
https://github.com/gvx/bitser/blob/4f2680317cdc8b6c5af7133835de5075f2cc0d1f/bitser.lua#L225-L226
In the above excerpt, `seen` is being used both as `seen[value]` for any `value` and `seen.len` to store the highest index. This seemed to me that it would cause a clash if `value == 'len'`. Indeed, this is what I get on testing:
```
> = table.concat(bitser.loads(bitser.dumps({ 'a', 'b', 3 })), ', ')
a, b, 3
> = table.concat(bitser.loads(bitser.dumps({ 'a', 'b', 'len', 3 })), ', ')
invalid value (nil) at index 3 in table for 'concat'
stack traceback:
        [builtin#92]: at 0x0100069ff0
        [C]: at 0x0100001230
```
One way around this is to have a top-level `local lenSentinel = {}` in the module and use `seen[lenSentinel]` instead.

**Comment by gvx** [comment]
Thank you very much! I think `seen` originally only held tables, but when its use was expanded, I never checked to see if that could cause problems. I will implement your fix.
