### ISSUE TITLE
Add cdata

### ISSUE THREAD

**Issue by MGeymer** [gvx/bitser#14]
My project uses ffi and tables with cdata variables. Can you add cdata support?

**Comment by gvx** [comment]
I haven't used cdata before, but I'll look into it. Could you share a simple example of the kind of data you'd want to serialize?

Because of restrictions on the ffi interface, it might be necessary to register ctypes like one registers classes.

**Comment by MGeymer** [comment]
cdata this is the ffi type. For example: 
local num1 = ffi.new ("int", 5)

**Comment by gvx** [comment]
Could you try the latest commit?

If it doesn't work, it might still work if you register the type of the cdata as a resource before dumping or loading, for example with:

    bitser.register('my_ctype', ffi.typeof(my_cdata))
    bitser.dumps(my_cdata)

Anonymous structs are not supported, but if you can find anything else that doesn't work, please let me know how to reproduce so I can add it to my tests.

**Comment by MGeymer** [comment]
Yes, individually, everything works well. But this caused an error. 
```
local var = {{ffi.new("int",1)},5,ffi.new("int",67)}
local str = bitser.dumps(var)
print(str)
local var1 = bitser.loads(str) -- Here is the error
```
Error
`bitser.lua:364: bad argument #1 to 'deserialize_value' (C type expected, got nil)`

**Comment by gvx** [comment]
Great catch. It turned out I was serializing references wrong if cdata's in the mix. It should work now, can you confirm?

**Comment by MGeymer** [comment]
Wow, good work, everything works, I hope there are no more errors.

**Comment by gvx** [comment]
Glad to be of service!
