### ISSUE TITLE
loadLoveFile crashes if file doesnt exists.

### ISSUE THREAD

**Issue by pirogronian** [gvx/bitser#16]
I suggest to return nil on error rather then calling assert. Or make on-error behaviour customizable.

**Comment by gvx** [comment]
Bitser uses `error` and `assert` throughout, to ensure early detection of problems and avoid silent data loss. I recommend using `pcall` to handle errors. For example, replacing:

    value = bitser.loadLoveFile(file_name)

with

    local status, value = pcall(bitser.loadLoveFile, file_name)
    if status then
         -- continue on as normal
    else
        -- handle the error, `value` contains the error message
    end
