### ISSUE TITLE
Functions?

### ISSUE THREAD

**Issue by WoolDoughnut310** [gvx/bitser#17]
Is there any way I can use bitser to serialize functions?

**Comment by gvx** [comment]
You can use `bitser.register('function name', your_function)`. Make sure to give each function you want to be able to serialize a unique function, and to make all calls to register resources before you dump or load anything.

This means you can't do something like `bitser.dumps(function() --[[ some closure ]] end)`.

**Comment by WoolDoughnut310** [comment]
But is there any way for me to be able to register some functions without without having to explicitly call `bitser.register('function_name', func)` each time?

**Comment by gvx** [comment]
I'm not sure what you're asking for. It's impossible to automatically register functions in Lua as far as I know, because functions don't have names (unlike, say, in Python).

**Comment by gittup** [comment]
This patch seems to work for me to support basic functions:

```
diff --git a/bitser.lua b/bitser.lua
index e929baa..7d4024c 100644
--- a/bitser.lua
+++ b/bitser.lua
@@ -242,7 +242,14 @@ local function write_cdata(value, seen)
        Buffer_write_raw(ffi.typeof('$[1]', ty)(value), len)
 end
 
-local types = {number = write_number, string = write_string, table = write_table, boolean = write_boolean, ["nil"] = write_nil, cdata = write_cdata}
+local function write_function(value)
+       local str = string.dump(value)
+       Buffer_write_byte(254)
+       write_number(#str)
+       Buffer_write_string(str)
+end
+
+local types = {number = write_number, string = write_string, table = write_table, boolean = write_boolean, ["nil"] = write_nil, cdata = write_cdata, ['function'] = write_function}
 
 serialize_value = function(value, seen)
        if seen[value] then
@@ -385,6 +392,10 @@ local function deserialize_value(seen)
                local read_into = ffi.typeof('$[1]', ctype)()
                Buffer_read_raw(read_into, len)
                return ctype(read_into[0])
+       elseif t == 254 then
+               local len = deserialize_value(seen)
+               local string = Buffer_read_string(len)
+               return add_to_seen(load(string), seen)
        else
                error("unsupported serialized type " .. t)
        end
```

It doesn't work if it's a closure with upvalues, but those weren't necessary for my use-case.

**Comment by gvx** [comment]
Thanks for sharing your work. I've deliberately not added this functionality to bitser, partly because of the security implementations (something that is even more serious now that I've added metatable support, which means that even something like `bitser.loads(foo).bar` can trigger code execution), but mostly because of the upvalue problem, which I am sure would cause many hard to diagnose bugs in user code, since calling `load(string.dump(f))` on a function `f` that has upvalues returns a function that works incorrectly.

**Comment by sonoro1234** [comment]
> because of the upvalue problem

It can be checked it has not upvalues with `debug.getupvalue(f, 1)==nil`
