### ISSUE TITLE
Segmentation Fault for bitser.dumpLoveFile

### ISSUE THREAD

**Issue by wistuba** [gvx/bitser#18]
Happy Holidays,
I was trying to use bitser to serialize some tables in the context of Love2D where I noticed that the game is sometimes crashing when saving. I created a small example for debugging reasons but was not able to fix it. Therefore, I would like to share my findings with you.

I ran following code with Love2D 11.0 and it is crashing on both Linux and Windows. Using Windows 10, I do not get an error message, with Linux it says "segmentation fault (core dumped)".

```
local sti = require("sti")
local bitser = require("bitser")

local mapFile = "map.lua"
bitser.dumpLoveFile(mapFile, love.filesystem.load("tiled_map.lua")())
local mapTable = bitser.loadLoveFile(mapFile)
sti(bitser.loadLoveFile(mapFile))
bitser.dumpLoveFile(mapFile, mapTable)
```

The error happens during the first call of `serialize_value` during the function call of the last line in above's snippet. If the `sti` function call is commented out, it is working without a problem.
This might be related to #9 but in this case it is about saving and not loading.

Some context: tiled_map.lua is a map created and exported with Tiled and returns on call a big table. For sake of completeness, I've also added the Tiled file to create this file. I don't think it is needed though.

I attached a minimal example to reproduce the bug below. Please note, that it may happen that program is sometimes not crashing. In that case, please rerun again, it happens quite frequently.
[minimal_example.zip](https://github.com/gvx/bitser/files/5735803/minimal_example.zip)
.

**Comment by gvx** [comment]
That's unfortunate. I will look into this, hopefully I can deliver a patch before New Year's Day. I appreciate the minimal example a lot. Happy holidays, I hope you have a lövely time!

**Comment by gvx** [comment]
The segfault has been fixed, but STI maps are still not supported, as `sti()` stores functions in the layers (`layer.update` and `layer.draw`). Functions are not supported by bitser and are unlikely to ever be supported. 😞

**Comment by wistuba** [comment]
Thanks a lot for the fast fix! I tried it in the larger context of my project and it addresses the issue I had before.

No worries about functions, serialization of tables with simple data types is sufficient for my use case.
