### ISSUE TITLE
Support the Classic class library

### ISSUE THREAD

**Issue by TheQuinbox** [gvx/bitser#32]
Was reading the usage file, and noticed you don't seem to support [Classic](https://github.com/rxi/classic). Could this possibly be added?

**Comment by gvx** [comment]
It looks like it has the same mechanism as `hump.class`, so it should work already! I'll try it out, see if I can confirm that it works, add corresponding tests, and add it to the README.

**Comment by gvx** [comment]
It seems to work, I added it to the README!
