### ISSUE TITLE
Document?

### ISSUE THREAD

**Issue by buckle2000** [gvx/bitser#7]
This is a good library. Is there any plan to add a document?

BTW, the last statement of `bitser.lua` is difficult to read.

**Comment by gvx** [comment]
Yeah, I realised yesterday I didn't actually have any documentation yet, just a snippet in the readme. Will add.

**Comment by gvx** [comment]
I've added documentation in [USAGE.md](/gvx/bitser/blob/master/USAGE.md), I hope that's satisfactory. As the last statement of `bitser.lua` is simply the public API, that should now be sufficiently documented.

If there's anything unclear or incorrect, please let me know or suggest changes yourself! 😄

**Comment by buckle2000** [comment]
The document is detailed enough.

One more thing, better include a link to https://love2d.org/wiki/Data in description of loadData
