### ISSUE TITLE
Saving and reloading very large tables causes a crash

### ISSUE THREAD

**Issue by amorphia78** [gvx/bitser#9]
Hi and thanks for bitser! Saving and then reloading a very large table causes a crash at the point of reloading on my windows 7 machine - a proper "this program has stopped working" crash. More information on why I need this and what I have tried is [here](https://love2d.org/forums/viewtopic.php?p=212556). Here is minimal LÖVE code to replicate the error (run, wait 10 s and press ESC, run again and press r):
```
bitser = require 'bitser'
drawReg = {}
regIndex = 1
function love.load()
	love.filesystem.setIdentity('megaAttackGame');
end
function love.update(dt)
	if love.keyboard.isDown("escape") then
		bitser.dumpLoveFile('replay.dat', drawReg )
		love.event.quit()
	elseif love.keyboard.isDown("r") then
		replayData = bitser.loadLoveFile('replay.dat')
	end
end
function love.draw(dt)
	for i=1,500 do
		registerVisible( 1, 1, "thing")
	end
end
function registerVisible( xPos, yPos, thingToDraw )
	drawReg[regIndex] = {
		timeStamp = os.clock(),
		x = xPos,
		y = yPos,
		t = thingToDraw
	}
	regIndex = regIndex + 1
	--Full version of function draws the thing as well
end
```

**Comment by zorggn** [comment]
To add to the above, even if the key detection is put into love.keypressed as to make sure no multiple-firings happen, the crash still occurs.
As i wrote in the forum thread, deserialize_value looks to be the likely function where it dies.

**Comment by pgimeno** [comment]
I believe this is a LuaJIT bug. Changing the code as follows makes it work as expected:

```diff
--- bitser-orig.lua	2018-11-05 23:19:06.051240968 +0100
+++ bitser.lua	2018-11-05 23:22:25.750320042 +0100
@@ -363,7 +363,8 @@
 end, loadLoveFile = function(fname)
 	local serializedData = love.filesystem.newFileData(fname)
 	Buffer_newDataReader(serializedData:getPointer(), serializedData:getSize())
-	return deserialize_value({})
+	local ret = deserialize_value({}) -- work around LuaJIT problem with tail calls
+	return ret
 end, loadData = function(data, size)
 	Buffer_newDataReader(data, size)
 	return deserialize_value({})
```

What I believe is happening here, is that the tail call causes execution to be transferred to `deserialize_value`, and more importantly, it causes `loadLoveFile` to be terminated. When `loadLoveFile` terminates, its local variables, most notably `serializedData`, are eligible for garbage collection. After some time, the garbage collection is effected, causing the Data object to be deallocated. This deallocation ultimately causes the segfault.

The patch above just converts the tail call into a regular call, preventing `loadLoveFile` from finishing until `deserialize_value` returns, thus preserving `serializedData`.

This problem is only visible with large files, because these are the ones triggering the garbage collection of `serializedData`.

**Comment by pgimeno** [comment]
I have managed to prove that indeed, GC is run and clears the `FileData` object during the execution of `deserialize_value`:

1. Modify bitser.lua as follows:

```diff
--- bitser-orig.lua	2018-11-05 23:19:06.051240968 +0100
+++ bitser.lua	2018-11-06 00:52:40.148784680 +0100
@@ -258,7 +258,10 @@
 	return #seen
 end
 
+local iter_count = 0
 local function deserialize_value(seen)
+  iter_count = iter_count + 1
+  print(iter_count)
 	local t = Buffer_read_byte()
 	if t < 128 then
 		--small int
```

2. Use this as main.lua:

```lua
local bitser = require 'bitser'

local function print_gc(p)
  print("GC is releasing " .. tostring(p))
  p:release()
  love.timer.sleep(1)
end

-- Local modified version of bitser.loadLoveFile:
local function loadLoveFile(fname)
  local serializedData, error = love.filesystem.newFileData(fname)
  assert(serializedData, error)

  -- Set the __gc metamethod of serializedData, to show when it's released
  local mt = getmetatable(serializedData)
  print("data = " .. tostring(serializedData))
  mt.__gc = print_gc

  return bitser.loadData(serializedData:getPointer(), serializedData:getSize())
end

-- This uses the file generated in the OP:
love.filesystem.setIdentity('megaAttackGame')
loadLoveFile('replay.dat')

collectgarbage('collect')
```

In my system, the output is:

```
data = FileData: 0x5595de13f990
1
2
3
4
5
6
...
45065
45066
45067
45068
45069
GC is releasing FileData: 0x55e761948470
        * here it pauses for 1 second *
Segmentation fault
```

When commenting out the `p:release()` line, GC is performed but not effective (it will leak memory), and the output is:

```
data = FileData: 0x559dd01f32f0
1
2
3
4
5
6
...
45065
45066
45067
45078
45069
GC is releasing FileData: 0x559dd01f32f0
        * here it pauses for 1 second *
45070
45071
...
3673998
3673999
3674000
3674001
3674002
3674003
```

To discard the `__gc` metamethod as a factor in *causing* the problem, I commented out the `mt.__gc = print_gc` line and got this output:

```
...
45065
45066
45067
45068
45069
Segmentation fault
```

When `loadLoveFile` is modified to remove the tail call by assigning it to a local, like in the patch in my previous post, the result is the expected:

```
data = FileData: 0x5556d5d55d00
1
2
3
4
5
6
7
8
...
3674001
3674002
3674003
GC is releasing FileData: 0x5556d5d55d00
        * here it pauses for 1 second *
```

Your mileage (the displayed numbers) may vary, depending on the length of the generated file and other factors, but the essence should be the same.

**Comment by gvx** [comment]
That is some amazing detective work! Thank you @pgimeno, I will implement your fix!

**Comment by pgimeno** [comment]
Thanks, I look forward to it :)

I called it a LuaJIT bug, but on second thought, it is not. A pointer is an even weaker reference than a weak reference, in that it can become invalid and still preserve its value. The object returned by `getPointer()` is a light userdata object containing a pointer. The existence of that object (the pointer) has no influence on whether the object pointed at (the `FileData` in this case) is cleaned up or not, so LuaJIT has the right of deallocating it when it feels it's no longer needed (it simply can't know there's still a pointer pointing to it).

It seems that when we start working with pointers in an environment with automatic garbage collection, we're in quicksand terrain, and extreme care must be taken at each step, as even the smallest misstep may make us sink.
